[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/chat"
  to   = "/.netlify/functions/chat"
  status = 200

[[redirects]]
  from = "/api/vision"
  to   = "/.netlify/functions/vision"
  status = 200

[[redirects]]
  from = "/api/ocrspace"
  to   = "/.netlify/functions/ocrspace"
  status = 200
