[build]
  publish = "."
  node_version = "18"

[functions]
  directory = "netlify/functions"
  included_files = ["netlify/functions/**"]

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
