# =========================
# Netlify configuration
# =========================

[build]
  functions = "netlify/functions"
  publish   = "."

[functions]
  directory    = "netlify/functions"
  node_bundler = "esbuild"

# --- Timeouts por función (ajusta según tu plan) ---
[functions.vqa]
  timeout = 26

[functions.vision]
  timeout = 26

[functions.ocrspace]
  timeout = 26

# NUEVO: T2I y Caption (subimos un poco T2I por latencia del modelo)
[functions.t2i]
  timeout = 55

[functions.caption]
  timeout = 30

# =========================
# Rutas limpias /api/*
# =========================

# Chat general (proxy a Groq/OpenAI)
[[redirects]]
  from = "/api/chat"
  to   = "/.netlify/functions/chat"
  status = 200

# Proxy alternativo (si llamas directo)
[[redirects]]
  from = "/api/groq"
  to   = "/.netlify/functions/groq-proxy"
  status = 200

# OCR (OCR.space)
[[redirects]]
  from = "/api/ocrspace"
  to   = "/.netlify/functions/ocrspace"
  status = 200

# Compatibilidad /api/ocr
[[redirects]]
  from = "/api/ocr"
  to   = "/.netlify/functions/ocrspace"
  status = 200

# (Legado) Visión clásica BLIP/VIT si la usas
[[redirects]]
  from = "/api/vision"
  to   = "/.netlify/functions/vision"
  status = 200

# VQA (Qwen-VL u otro)
[[redirects]]
  from = "/api/vqa"
  to   = "/.netlify/functions/vqa"
  status = 200

# NUEVO: Text → Image
[[redirects]]
  from = "/api/t2i"
  to   = "/.netlify/functions/t2i"
  status = 200

# NUEVO: Image → Text (caption)
[[redirects]]
  from = "/api/caption"
  to   = "/.netlify/functions/caption"
  status = 200

# =========================
# Headers
# =========================

# Seguridad básica global
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# CORS para tus funciones (por si navegas desde otro origen/subdominio)
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# (Opcional) SPA fallback; si usas rutas del lado del cliente, descomenta:
# [[redirects]]
#   from = "/*"
#   to   = "/index.html"
#   status = 200
