[build]
  functions = "netlify/functions"

# Redirecciones limpias desde /api/* a Functions
[[redirects]]
  from = "/api/ocr"
  to = "/.netlify/functions/ocr"
  status = 200

[[redirects]]
  from = "/api/vision/caption"
  to = "/.netlify/functions/vision-caption"
  status = 200

[[redirects]]
  from = "/api/vision/qa"
  to = "/.netlify/functions/vision-qa"
  status = 200
