# =========================
# Netlify configuration
# =========================

[build]
  functions = "netlify/functions"
  publish   = "."

[functions]
  directory    = "netlify/functions"
  node_bundler = "esbuild"

# --- Timeouts por función (ajusta según tu plan) ---
[functions.chat]
  timeout = 30

[functions.groq-proxy]
  timeout = 30

[functions.vision]
  timeout = 30

[functions.t2i]
  timeout = 55   # más alto por latencia de generación

# =========================
# Rutas limpias /api/*
# =========================

# Chat general (proxy a Groq/OpenAI)
[[redirects]]
  from = "/api/chat"
  to   = "/.netlify/functions/chat"
  status = 200

# Proxy alternativo (si llamas directo)
[[redirects]]
  from = "/api/groq"
  to   = "/.netlify/functions/groq-proxy"
  status = 200

# Vision (describe, OCR, QA sobre imágenes)
[[redirects]]
  from = "/api/vision"
  to   = "/.netlify/functions/vision"
  status = 200

# Text → Image
[[redirects]]
  from = "/api/t2i"
  to   = "/.netlify/functions/t2i"
  status = 200

# hf-ping (opcional, chequeo de conexión)
[[redirects]]
  from = "/api/hf-ping"
  to   = "/.netlify/functions/hf-ping"
  status = 200

# =========================
# Headers
# =========================

# Seguridad básica global
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# CORS para tus funciones
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"

# (Opcional) SPA fallback
# [[redirects]]
#   from = "/*"
#   to   = "/index.html"
#   status = 200
