[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

# Rutas limpias tipo /api/*
[[redirects]]
from = "/api/chat"
to = "/.netlify/functions/chat"
status = 200

[[redirects]]
from = "/api/groq"
to = "/.netlify/functions/groq-proxy"
status = 200

[[redirects]]
from = "/api/ocr"
to = "/.netlify/functions/ocrspace"
status = 200

[[redirects]]
from = "/api/vision"
to = "/.netlify/functions/vision"
status = 200
