[build]
  publish = "."
  functions = "netlify/functions"

# Mapeo amigable: /api/chat -> /.netlify/functions/chat
[[redirects]]
  from = "/api/chat"
  to = "/.netlify/functions/chat"
  status = 200
  force = true
